# Generated by Django 5.1.1 on 2024-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('renta_imponible', models.FloatField()),
                ('num_cargas', models.IntegerField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('prevision_actual', models.CharField(max_length=50)),
                ('cambio_preferente', models.CharField(max_length=50)),
                ('valor_uf', models.FloatField()),
            ],
        ),
    ]
