# Generated by Django 5.1.1 on 2024-10-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
