# Generated by Django 5.1.1 on 2024-10-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_formulariodatos_valor_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodatos',
            name='valor_uf',
        ),
    ]
