# Generated by Django 5.1.1 on 2024-10-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_formulariodatos_valor_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariodatos',
            name='resultado_final',
            field=models.CharField(default='Valor predeterminado', max_length=255),
        ),
        migrations.AddField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.CharField(default='Valor predeterminado', max_length=255),
        ),
    ]
