# Generated by Django 5.1.1 on 2024-10-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formulariodatos_resultado_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodatos',
            name='resultado_final',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.FloatField(),
        ),
    ]
