# Generated by Django 5.1.1 on 2024-10-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_formulariodatos_resultado_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodatos',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='renta_imponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='resultado_final',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
