# Generated by Django 5.1.1 on 2024-10-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_formulariodatos_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariodatos',
            name='monto_dispuesto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='renta_imponible',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='resultado_final',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.FloatField(),
        ),
    ]
