# Generated by Django 5.1.1 on 2024-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_formulariodatos_resultado_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodatos',
            name='valor_uf',
            field=models.FloatField(default=0.0),
        ),
    ]
