# Generated by Django 5.1.1 on 2024-10-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_formulariodatos_valor_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='app.formulariodatos')),
            ],
        ),
    ]
