# Generated by Django 5.1.1 on 2024-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_carga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariodatos',
            old_name='ciudad',
            new_name='comuna',
        ),
    ]
