# Generated by Django 5.1.1 on 2024-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_ciudad_formulariodatos_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodatos',
            name='monto_dispuesto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='resultado_final',
            field=models.IntegerField(),
        ),
    ]
