# Generated by Django 5.1.1 on 2024-10-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_formulariodatos_monto_dispuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_nombre', models.CharField(max_length=255)),
                ('region', models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='app.region')),
            ],
        ),
    ]
