# Generated by Django 5.1.1 on 2024-11-06 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('renta_imponible', models.FloatField()),
                ('num_cargas', models.IntegerField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('prevision_actual', models.CharField(max_length=50)),
                ('cambio_preferente', models.CharField(max_length=50)),
                ('valor_uf', models.FloatField(default=0.0)),
                ('resultado_final', models.IntegerField()),
                ('monto_dispuesto', models.IntegerField(blank=True, null=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.comunas')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='app.formulariodatos')),
            ],
        ),
        migrations.AddField(
            model_name='comunas',
            name='region',
            field=models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='app.region'),
        ),
    ]
