# Generated by Django 5.1.1 on 2024-11-06 23:28

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12, validators=[app.models.validar_telefono_chileno])),
            ],
        ),
        migrations.AlterField(
            model_name='formulariodatos',
            name='telefono',
            field=models.CharField(max_length=12, validators=[app.models.validar_telefono_chileno]),
        ),
        migrations.AddField(
            model_name='formulariodatos',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asesor'),
        ),
    ]
